title: My Personal Website
description: Welcome to my personal website!
url: "https://lorenzsp.github.io"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Optional: Include navigation links if the theme supports them
nav:
  - home: /
  - about: /about
  - contact: /contact

# Optional: Set baseurl if your site is hosted in a subdirectory
# baseurl: "/my-site"

# Optional: Social media links
social:
  github: https://github.com/lorenzsp

# Other optional settings
markdown: kramdown
